export enum Industry {
  RESTAURANTS = 'Restaurants',
  CORPORATE = 'Corporate',
  CONSTRUCTION_AND_REAL_ESTATE = 'Construction and RealEstate',
  EDUCATION = 'Education',
  ENERGY = 'Energy',
  FINANCE = 'Finance',
  HEALTHCARE_AND_FITNESS = 'Healthcare and Fitness',
  INDUSTRIAL = 'Industrial',
  CHEMICAL = 'Chemical',
  TRANSPORTATION_AND_LOGISTICS = 'Transportation and Logistics',
  RETAILERS = 'Retailers',
  HOSPITALITY = 'Hospitality',
  TECH = 'Tech',
  SERVICES = 'Services',
  ARTS = 'Arts',
  BEAUTY = 'Beauty',
  CONSULTANCY = 'Consultancy',
  MEDIA = 'Media',
  TEXTILE = 'Textile',
  TRAVEL = 'Travel',
  ADVENTURE_AND_ACTIVITIES = 'Adventure and Activities',
}
